# configs/dataset/Anthem.yaml
params:
    model_count: 5
    base_model_count: 1
    max_len_hla: 34
    max_len_pep: 15
    fusion:
    predictor:

train:
  name:  ${train.name}
  epochs: 1000

  loss_delta: 1e-4
  dropout : 0.2
  batch_size: 1024
  grad_clip: 0.5

  start_lr: 1e-3
  weight_decay: 1e-5

  # scheduler
  scheduler_patience: 8
  cooldown: 4
  min_lr: 1e-6

  scheduler_factor: 0.2

  # early_stop
  callback_patience: 10
  # ModelCheckPoint
  period: 1

model:










