# configs/config.yaml
defaults:
  - _self_
  - model: lyraMHC
#   Anthem/transpMHC
  - dataset: transpMHC

experiment:
  # select model LyraMHC
  model: "LyraMHC"
  # Name of the experiment.
  # This value determines the output directory:
  # outputs/${train.name}/${experiment.name}/
  # For example:
  # outputs/transpMHC_train/Debug/
  name: "TCR_Debug"
  # Short experiment note
  description: "blosum"
  training: "True"

  version: "1.0"
  best_model_path: "outputs/transpMHC_train/Debug/2026-03-13_21-15-57/checkpoints/best_model.pt"


train:
  device: "cuda"
  cpu_device: "cpu"
  seed: 6
  # Feature encoding methods for sequence representation.
  # Available options:
  # one_hot / blosum / blosum80 / physical / EDSSMat62 / N_blosum / one_hot+blosum
  encoding_method: "blosum"
  encoding_method2: "blosum"
  # train.name: Anthem_train / transpMHC_train
  name: "transpMHC_train"
  # select task: pMHC / TCR
  task: "pMHC"
  data_path: "data/processed/${dataset.train.name}"
  train_step: "True"

encode:
  one_hot: 20
  blosum: 23
  blosum80: 25
  physical: 11
  EDSSMat62: 24
  N_blosum: 23
  one_hot+blosum: 43

hydra:
  run:
    dir: outputs/${dataset.train.name}/${experiment.name}/${now:%Y-%m-%d_%H-%M-%S}
