# configs/config.yaml
defaults:
  - _self_
  - model: lyraMHC        # 默认加载 configs/model/lyra_base.yaml
#  - dataset: Anthem/transpMHC
  - dataset: transpMHC
#  - paths: default

experiment:
  # LyraMHC
  model: "StarLyraMHC"
  name: "StarLyraMHC_beta3.0"

  description: "start_lr: 1e-3 ,  batch 1024 dropout 0.2  S4D is 5 4 PGC 1 1"
  training: "True"


  tags: ["baseline", "lyra"]
  version: "1.0"
  best_model_path: "outputs/transpMHC_train/physical/2026-01-05_19-30-47/checkpoints/best_model.pt"


train:
  device: "cuda"
  cpu_device: "cpu"
  seed: 2

  #   'one_hot+blosum': one_hot_PLUS_blosum_encode, 43
  #   'one_hot': one_hot_encode, 20
  #  'physical': physical_encode, 11
  #  'blosum': blosum_encode, 23
  #  'blosum80': blosum80_encode, 25
  #  'EDSSMat62': EDSSMat62_encode, 24
  #  'N_blosum': N_blosum_encode 23

  encoding_method: "EDSSMat62"
  encoding_method2: "EDSSMat62"
  # Anthem_train / transpMHC_train
  name: "transpMHC_train"
  # pMHC / TCR
  task: "pMHC"
  data_path: "data/processed/${dataset.train.name}"
  train_step: "True"


hydra:
  run:
    dir: outputs/${dataset.train.name}/${experiment.name}/${now:%Y-%m-%d_%H-%M-%S}
